### ISSUE TITLE
spring boot2.2.0： jasypt-spring-boot2.1.0 Failed to bind properties under

### ISSUE THREAD

**Issue by lunxian8** [ulisesbocchio/jasypt-spring-boot#161]
Upgrading spring boot2.2.0 found that a reference to jasypt2.1 caused the spring-@configurationproperties injection configuration error

**Comment by huxudong** [comment]
application.yml 
add  proxy-property-sources: true 

example:

```
jasypt:
  encryptor:
    password: password
    proxy-property-sources: true
```
