### ISSUE TITLE
version of 3.0.2 is not supperted spring-boot 2.2.x

### ISSUE THREAD

**Issue by Comven** [ulisesbocchio/jasypt-spring-boot#189]
upgrade spring-boot from 2.1.x to 2.2.x, it can't work with error on start
````
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'content' to java.lang.String:

    Reason: Failed to bind properties under 'content' to java.lang.String

Action:

Update your application's configuration

````
the encrypted parameter is configured like this
````
content=ENC(2iyMyv0EupM0Ej/nTTIp+Q==)
````

**Comment by Comven** [comment]
Sorry, it's my fault. I didn't read the upgrade instructions carefully

**Comment by agramar** [comment]
Changed default encryption to PBEWITHHMACSHA512ANDAES_256
To keep your encrypted properties with previous default config use:
```yaml
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
```
