### ISSUE TITLE
Error trying to use safer algorithms

### ISSUE THREAD

**Issue by Hugo2k13** [ulisesbocchio/jasypt-spring-boot#221]
**List of algorithms that works well:**
- PBEWithMD5AndDES
- PBEWithMD5AndTripleDES
- PBEWithSHA1AndDESede
- PBEWithSHA1AndRC2_40
- PBEWithSHA1AndRC2_128
- PBEWithSHA1AndRC4_40
- PBEWithSHA1AndRC4_128

**List of algorithms that doesn't work:**
- PBEWithHmacSHA1AndAES_128
- PBEWithHmacSHA224AndAES_128
- PBEWithHmacSHA256AndAES_128
- PBEWithHmacSHA384AndAES_128
- PBEWithHmacSHA512AndAES_128
- PBEWithHmacSHA1AndAES_256
- PBEWithHmacSHA224AndAES_256
- PBEWithHmacSHA256AndAES_256
- PBEWithHmacSHA384AndAES_256
- PBEWithHmacSHA512AndAES_256
- PBKDF2WithHmacSHA1
- PBKDF2WithHmacSHA224
- PBKDF2WithHmacSHA256
- PBKDF2WithHmacSHA384
- PBKDF2WithHmacSHA512

Unfortunately these algorithms that aren't working are the same that I would like to use, due to their greater security.

Error shown:
```
Description:

Failed to bind properties under 'spring.datasource.password' to java.lang.String:

    Reason: Failed to bind properties under 'spring.datasource.password' to java.lang.String

Action:

Update your application's configuration
```
Pom.xml:
```
<dependency>
	<groupId>com.github.ulisesbocchio</groupId>
	<artifactId>jasypt-spring-boot-starter</artifactId>
	<version>3.0.3</version>
</dependency>
```

Application.yml:
```
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithHmacSHA1AndAES_128
    password: ${KEY}
spring:
  profiles: dev
  datasource:
    url: 'jdbc:sqlserver://localhost:14331;databaseName=test'
    username: user
```
external.properties:

`spring.datasource.password = ENC(LIXLVqn7nPwGpIJvRywI3xOHGsv/XDeNRuXD5dWdnxc=)`

**_Example_** 

I'm getting spring.datasource.password through jasypt-1.9.2.jar with the following command:
`java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input = "test" password = secretKey algorithm = PBEWithHmacSHA1AndAES_128`

Output:
`LIXLVqn7nPwGpIJvRywI3xOHGsv/XDeNRuXD5dWdnxc=`
