### ISSUE TITLE
[Feature: Deep intergration whit the nacos config]

### ISSUE THREAD

**Issue by lishuo5263** [ulisesbocchio/jasypt-spring-boot#303]
extension-configs:   # multiple config  overload
          - data-id: obvious-env-config-role.yaml #db
            group: PWD_CHANGE
            refresh: true
          - data-id: obvious-env-config-role.yaml #db
            group: PWD_CHANGE2
            refresh: true
        #Only support one shared yaml
        shared-configs:
          - data-id: shared-common-param.yaml
            group: SHARED_COMMON
            refresh: true

So,such as this config,one jasypt password to decrypt\encrypt not enougth.We need a new common jasypt password to  decrypt\encrypt Naocs shared-configs、extension-configs.

**Comment by lishuo5263** [comment]
```
spring:
  cloud:
      config:
        username: nacos
        server-addr: localhost8848
        namespace: 284f09b1-2e9e-473a-b084-0ec83473df13
        group: PWD_CHANGE
        file-extension: yaml
        extension-configs:   # multiple config  overload
          - data-id: obvious-env-config-role.yaml #db
            group: PWD_CHANGE
            refresh: true
          - data-id: obvious-env-config-role.yaml #db
            group: PWD_CHANGE2
            refresh: true
        shared-configs:
          - data-id: shared-common-param.yaml
            group: SHARED_COMMON
            refresh: true
```
