### ISSUE TITLE
Spring Cloud Starter Config properties are not decrypted

### ISSUE THREAD

**Issue by diegomarzo** [ulisesbocchio/jasypt-spring-boot#311]
In our project we are using Jasypt and Spring Cloud Config Client

Our problem is that the password property is not getting decrypted.

```
spring:
  application:
    name: connector
  profiles:
    active: dev
  config:
    import: configserver:http://XXXXXXXXX
  cloud:
    config:
      username: connector-app
      password: ENC(XXXXXXXXXXXXXXX)

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWITHSHA1ANDRC2_40
    password: ${JASYPT_SECRET}
```

If we change the password for the non encrypted password all works fine.

These are our dependencies:
```
    implementation("org.springframework.cloud:spring-cloud-starter-config:3.1.1")
    implementation("com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.4")
```

Our main:
```
fun main(args: Array<String>) {
    runApplication<ConnectorApplication>(*args)
}
```

And we also tried with:
```
fun main(args: Array<String>) {
    SpringApplicationBuilder()
        .environment(StandardEncryptableEnvironment())
        .sources(ConnectorApplication::class.java).run(*args)
}
```

But we had the same issue.

If the property encrypted is not the cloud.config one it works perfectly, we try adding:

```
myprop:
  passoword: ENC(XXXXXXXXXX)
```

And all worked fine.

The only errors in the logs are the ones related with non being able to create our own beans due to the lack of properties, since they have not been retrieved from the server.

**Comment by diegomarzo** [comment]
So after a bunch of investigation we found the "issue"

I will write the workaround here just in case it bites someone else:

We need to had a "bootstrap.yml" file, and there we will configure JASYPT and Spring Cloud Config Client:

```
spring:
  profiles:
    active: dev
  cloud:
    config:
      username: connector-app
      password: ENC(XXXXXXXX)
      uri: http://XXXXX
      enabled: true

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWITHSHA1ANDRC2_40
    password: ${JASYPT_SECRET}
    bootstrap: true
```

Note that we have changed the Spring cloud configuration section, and instead of being `config.import `now all inside the `cloud.config` section. Also enabled flag is set as true.

For the JASYPT section we use the password in an environment variable (that is why we have `${JASYPT_SECRET}` like that.
Note also the `boostrap : true`

Finally we need to have in gradle the dependency for bootstrap:

`implementation("org.springframework.cloud:spring-cloud-starter-bootstrap:3.1.1")`

Even if we have find a work around it feels very weird, I would like to know your thoughts about it.

Another funny point is that if you put the spring application name in bootstrap instead of the application yml, the cloud client doesn't resolves and it names the app as "application".

All these weird stuff looks really like Spring Cloud issues and nothing to do with our lovely Jasypt lib

I'm closing the issue now.
