### ISSUE TITLE
How to avoid decryption?

### ISSUE THREAD

**Issue by TioCoding** [ulisesbocchio/jasypt-spring-boot#93]
Hi, I'm starting to document about jasypt, and I think it's great, I've been testing it but I ran into a problem. I have created my key to perfection, this is my .yml file:

```
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: secretkey

variable:
  secret-var: ENC(vILHJqGeG2UaxM3l5kTT0UeDPU4ZdWjYmFlpO9Kk0QtERbt0EX9IUQ==)
```
The value I try to hide is this:

`http://localhost:8080/api/`

But I found this page, where putting the value, the password of the key, you get the result:

Page: https://www.devglan.com/online-tools/jasypt-online-encryption-decryption

![jasypt](https://user-images.githubusercontent.com/22163898/43366590-df638dac-9305-11e8-9301-e0c15918c92f.PNG)

How could I avoid this? since the .yml file can be extracted from a desktop application (.jar file)

Thanks and regards.
